# Generated by Django 5.1.7 on 2025-04-20 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamHealthVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('teamwork', 'Teamwork'), ('pawns', 'Pawns or Players'), ('mission', 'Mission'), ('codebase', 'Health of Codebase'), ('process', 'Suitable Process'), ('value', 'Delivering Value'), ('learning', 'Learning'), ('speed', 'Speed'), ('release', 'Easy to Release'), ('fun', 'Fun')], max_length=20)),
                ('color', models.CharField(choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], max_length=10)),
                ('score', models.IntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
