# Generated by Django 5.1.7 on 2025-04-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_team_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('team_number', models.CharField(max_length=50)),
                ('department_number', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('engineer', 'Engineer'), ('teamleader', 'Team Leader'), ('departmentleader', 'Department Leader'), ('seniormanager', 'Senior Manager'), ('admin', 'Admin')], default='engineer', max_length=20)),
                ('registered', models.BooleanField(default=False)),
            ],
        ),
    ]
