# Generated by Django 5.1.7 on 2025-04-26 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('teamleader', 'Team Leader'), ('departmentleader', 'Department Leader'), ('seniormanager', 'Senior Manager')], default='engineer', max_length=20),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='my_app.team')),
            ],
        ),
    ]
