# Generated by Django 5.1.7 on 2025-04-29 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_employee_name_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='my_app.department'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
